name: Build and Push Images to Registry

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - image_name: chain
            package: chain
          - image_name: governance
            package: governance
          - image_name: pos
            package: pos
          - image_name: rewards
            package: rewards
          - image_name: parameters
            package: parameters
          - image_name: transaction
            package: transactions
          - image_name: webserver
            package: webserver

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          build-args: |
            PACKAGE=${{ matrix.package }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ matrix.image_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
