name: Build and Push Images to Registry

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - image_name: chain
            package: chain
          - image_name: governance
            package: governance
          - image_name: pos
            package: pos
          - image_name: rewards
            package: rewards
          - image_name: parameters
            package: parameters
          - image_name: transaction
            package: transactions
          - image_name: webserver
            package: webserver

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Initialize and update submodule
        run: |
          git submodule init
          git submodule update --init --recursive

      - name: Checkout tag in submodule
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cd namada-indexer
          git fetch --all
          git checkout ${GITHUB_REF#refs/tags/}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for Docker
        id: meta
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
          else
            echo "version=latest" >> $GITHUB_OUTPUT
          fi

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./namada-indexer
          file: ./namada-indexer/Dockerfile
          build-args: |
            PACKAGE=${{ matrix.package }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ matrix.image_name }}:${{ steps.meta.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
